config/routes.rb
Rails.application.routes.draw do
  resources :bookings
  resources :salaries
  resources :employs
  resources :expenses
  resources :rooms
  devise_for :users
  get '/dashboard' ,to:  'static_files#dashboard'
  root 'static_files#dashboard'
end

app/views/navbar/_menu.html.erb
   <nav class="navbar navbar-default navbar-cls-top " role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".sidebar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" style="color: #362929 ;background-color: #FFFFFF" href="/">B&B HOTEL</a> 
            </div>
  <div style="color: black;
padding: 15px 50px 5px 50px;
float: right;
font-size: 16px;"> Last access : <%= current_user.last_sign_in_at.strftime("%d %B %Y") %>  &nbsp; 

<%= link_to "Logout" ,  destroy_user_session_path , method: :delete , class: "btn btn-danger square-btn-adjust" %>
 </div>
        </nav>   
           <!-- /. NAV TOP  -->
                <nav class="navbar-default navbar-side" role="navigation">
            <div class="sidebar-collapse">
                <ul class="nav" id="main-menu">
        <li class="text-center">
        <%= image_tag 'find_user.png' , class: "user-image img-responsive" %>
          </li>
        
          
                    <li  >
                        <%= link_to(dashboard_path)  do %>
                        <i class="fa fa-square-o fa-3x "> </i> Dashboard
                        <% end %>
                    </li>


                    <li  >
                   

                        <%= link_to( bookings_path) do %>
                        <i class="fa fa-edit fa-3x "> </i> Booking 
                        <% end %>

                       
                    </li>     


                    <li>
                        <%= link_to(rooms_path)  do %>
                        <i class="fa fa-square-o fa-3x "> </i> Rooms
                        <% end %>
                    </li>

                     <li>

                        <%= link_to(expenses_path) do %>
                        <i class="fa fa-desktop fa-3x "> </i> Expenses
                        <% end %>
                        
                    </li>

                    <li>

                     <%= link_to( employs_path) do %>
                        <i class="fa fa-qrcode fa-3x "> </i> Employees 
                        <% end %>
                        
                    </li>
                    <li  >
                     <%= link_to(salaries_path) do %>
                        <i class="fa fa-edit fa-3x "> </i> Salaries
                        <% end %>

                    </li> 
    
                </ul>
               
            </div>
            
        </nav> 