config/routes.rb
Rails.application.routes.draw do
  resources :bookings
  resources :salaries
  resources :employs
  resources :expenses
  resources :rooms
  devise_for :users
  get '/dashboard' ,to:  'static_files#dashboard'
  root 'static_files#dashboard'
end

app/models/employ.rb
# == Schema Information
#
# Table name: employs
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  cnic       :string(255)
#  phone_no   :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Employ < ApplicationRecord
end

app/controllers/employs_controller.rb
class EmploysController < ApplicationController
  before_action :set_employ, only: [:show, :edit, :update, :destroy]

  # GET /employs
  # GET /employs.json
  def index
    @employs = Employ.all
  end

  # GET /employs/1
  # GET /employs/1.json
  def show
  end

  # GET /employs/new
  def new
    @employ = Employ.new
  end

  # GET /employs/1/edit
  def edit
  end

  # POST /employs
  # POST /employs.json
  def create
    @employ = Employ.new(employ_params)

    respond_to do |format|
      if @employ.save
        format.html { redirect_to employs_path, notice: 'Employ was successfully created.' }
        format.json { render :show, status: :created, location: @employ }
      else
        format.html { render :new }
        format.json { render json: @employ.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employs/1
  # PATCH/PUT /employs/1.json
  def update
    respond_to do |format|
      if @employ.update(employ_params)
        format.html { redirect_to employs_path, notice: 'Employ was successfully updated.' }
        format.json { render :show, status: :ok, location: @employ }
      else
        format.html { render :edit }
        format.json { render json: @employ.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employs/1
  # DELETE /employs/1.json
  def destroy
    @employ.destroy
    respond_to do |format|
      format.html { redirect_to employs_url, notice: 'Employ was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employ
      @employ = Employ.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employ_params
      params.require(:employ).permit(:name, :cnic, :phone_no , :salary)
    end
end

app/helpers/employs_helper.rb
module EmploysHelper
end

app/views/employs/_form.html.slim
= simple_form_for(@employ) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.input :cnic
    = f.input :phone_no
    = f.input :salary

  .form-actions
    = f.button :submit ,'Add Employee'

app/views/employs/edit.html.slim
div.row
	div.col-lg-4
	div.col-lg-4


		h1 Editing employ

		== render 'form'

		= link_to 'Back', employs_path

app/views/employs/index.html.erb
  <div id="page-wrapper" >
            <div id="page-inner">
                <div class="row">
                    <div class="col-md-12">
                     <h2>All Employees</h2>   
                        <h5>Welcome , Love to see you back. </h5>
                       
                    </div>
                </div>
                 <!-- /. ROW  -->
                 <hr />
               
            <div class="row">
                <div class="col-md-12">
                    <!-- Advanced Tables -->
                    <div class="panel panel-default">
                        <div class="panel-heading">
                             
                             <%= link_to 'Add New Employ' , new_employ_path , class: "btn btn-success btn " %> 
                        </div>
                        <div class="panel-body">
                            <div class="table-responsive">
                                <table class=" datatable table table-striped table-bordered table-hover datatable" id="dataTables-example ">
                                    <thead>
                                        <tr>
                                            <th>Name</th>
                                            <th>CNIC</th>
                                            <th>Phone</th>
                                            <th>Salary</th>
                                            <th>Edit</th>
                                            <th>Delete</th>                                
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <%- @employs.each do |e| %>
                                        <tr>
                                           <td> <%= e.name%> </td>
                                           <td> <%= e.cnic %> </td>
                                           <td> <%= e.phone_no %> </td>
                                           <td> <%= e.salary %> </td>
                                            <td><%= link_to 'edit' , edit_employ_path(e) , class: "btn btn-info btn-xs" %></td>
                                            <td><%= link_to 'delete' , e , method: :delete , class: "btn btn-danger btn-xs" %></td>
                                        </tr>

                                        
                                        <% end %>
                                    </tbody>
                                </table>
                            </div>
                            
                        </div>
                    </div>
                </div>
            </div>

app/views/employs/new.html.slim
div.row
	div.col-lg-4
	div.col-lg-4

		h1 New employee

		== render 'form'
		br
		= link_to 'Back', employs_path , class: "btn btn-default"

app/views/employs/show.html.slim
p#notice = notice

p
  strong Name:
  = @employ.name
p
  strong Cnic:
  = @employ.cnic
p
  strong Phone no:
  = @employ.phone_no

= link_to 'Edit', edit_employ_path(@employ)
'  |
= link_to 'Back', employs_path