config/routes.rb
Rails.application.routes.draw do
  resources :bookings
  resources :salaries
  resources :employs
  resources :expenses
  resources :rooms
  devise_for :users
  get '/dashboard' ,to:  'static_files#dashboard'
  root 'static_files#dashboard'
end

app/models/salary.rb
# == Schema Information
#
# Table name: salaries
#
#  id         :integer          not null, primary key
#  employ_id  :integer
#  amount     :integer
#  detail     :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Salary < ApplicationRecord
  belongs_to :employ

  before_save :create_expence

  def create_expence
  	Expense.create(amount: self.amount , detail: Employ.find(self.employ_id).name + "-"+self.detail , date: Date.today )
  end

end

app/controllers/salaries_controller.rb
class SalariesController < ApplicationController
  before_action :set_salary, only: [:show, :edit, :update, :destroy]

  # GET /salaries
  # GET /salaries.json
  def index
    @salaries = Salary.all
  end

  # GET /salaries/1
  # GET /salaries/1.json
  def show
  end

  # GET /salaries/new
  def new
    @salary = Salary.new
  end

  # GET /salaries/1/edit
  def edit
  end

  # POST /salaries
  # POST /salaries.json
  def create
    @salary = Salary.new(salary_params)

    respond_to do |format|
      if @salary.save
        format.html { redirect_to salaries_path, notice: 'Salary was successfully created.' }
        format.json { render :show, status: :created, location: @salary }
      else
        format.html { render :new }
        format.json { render json: @salary.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /salaries/1
  # PATCH/PUT /salaries/1.json
  def update
    respond_to do |format|
      if @salary.update(salary_params)
        format.html { redirect_to salaries_path, notice: 'Salary was successfully updated.' }
        format.json { render :show, status: :ok, location: @salary }
      else
        format.html { render :edit }
        format.json { render json: @salary.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /salaries/1
  # DELETE /salaries/1.json
  def destroy
    @salary.destroy
    respond_to do |format|
      format.html { redirect_to salaries_url, notice: 'Salary was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_salary
      @salary = Salary.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def salary_params
      params.require(:salary).permit(:employ_id, :amount, :detail )
    end
end

app/helpers/salaries_helper.rb
module SalariesHelper
end

app/views/salaries/_form.html.slim
= simple_form_for(@salary) do |f|
  = f.error_notification

  .form-inputs
    = f.association :employ
    = f.input :amount
    = f.input :detail

  .form-actions
    = f.button :submit

app/views/salaries/edit.html.slim
div.row
	div.col-lg-4
	div.col-lg-4
		h1 Editing salary

		== render 'form'
		= link_to 'Back', salaries_path

app/views/salaries/index.html.erb
  <div id="page-wrapper" >
            <div id="page-inner">
                <div class="row">
                    <div class="col-md-12">
                     <h2>All Salaries</h2>   
                        <h5>Welcome , Love to see you back. </h5>
                       
                    </div>
                </div>
                 <!-- /. ROW  -->
                 <hr />
               
            <div class="row">
                <div class="col-md-12">
                    <!-- Advanced Tables -->
                    <div class="panel panel-default">
                        <div class="panel-heading">
                             
                             <%= link_to 'Add New salary' , new_salary_path , class: "btn btn-success btn " %> 
                        </div>
                        <div class="panel-body">
                            <div class="table-responsive">
                                <table class=" datatable table table-striped table-bordered table-hover datatable" id="dataTables-example ">
                                    <thead>
                                        <tr>
                                            <th>Name</th>
                                            <th>Amount</th>
                                            <th>Detail</th>

                                            <th>Date</th>
                                            <th>Edit</th>
                                            <th>Delete</th>                                
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <%- @salaries.each do |s| %>
                                        <tr>
                                           <td> <%= s.employ.name%> </td>
                                           <td> <%= s.amount %> </td>
                                           <td> <%= s.detail %> </td>
                                           <td> <%= s.created_at.strftime("%d %B %Y") %> </td>
                                            <td><%= link_to 'edit' , edit_salary_path(s) , class: "btn btn-info btn-xs" %></td>
                                            <td><%= link_to 'delete' , s , method: :delete , class: "btn btn-danger btn-xs" %></td>
                                        </tr>

                                        
                                        <% end %>
                                    </tbody>
                                </table>
                            </div>
                            
                        </div>
                    </div>
                </div>
            </div>

app/views/salaries/new.html.slim
div.row
	div.col-lg-4
	div.col-lg-4
		h1 New salary

		== render 'form'

		= link_to 'Back', salaries_path

app/views/salaries/show.html.slim
p#notice = notice

p
  strong Employ:
  = @salary.employ
p
  strong Amount:
  = @salary.amount
p
  strong Detail:
  = @salary.detail

= link_to 'Edit', edit_salary_path(@salary)
'  |
= link_to 'Back', salaries_path