config/routes.rb
Rails.application.routes.draw do
  resources :bookings
  resources :salaries
  resources :employs
  resources :expenses
  resources :rooms
  devise_for :users
  get '/dashboard' ,to:  'static_files#dashboard'
  root 'static_files#dashboard'
end

app/models/room.rb
# == Schema Information
#
# Table name: rooms
#
#  id         :integer          not null, primary key
#  room_no    :string(255)
#  avalable   :boolean
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Room < ApplicationRecord
	has_many :room_bokings , inverse_of: :room , dependent: :destroy
	has_many :bookings , through: :room_bokings
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: [:show, :edit, :update, :destroy]

  # GET /rooms
  # GET /rooms.json
  def index
    @rooms = Room.all
  end

  # GET /rooms/1
  # GET /rooms/1.json
  def show
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms
  # POST /rooms.json
  def create
    @room = Room.new(room_params)

    respond_to do |format|
      if @room.save
        format.html { redirect_to rooms_path, notice: 'Room was successfully created.' }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1
  # PATCH/PUT /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to rooms_path, notice: 'Room was successfully updated.' }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1
  # DELETE /rooms/1.json
  def destroy
    @room.destroy
    respond_to do |format|
      format.html { redirect_to rooms_url, notice: 'Room was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def room_params
      params.require(:room).permit(:room_no, :avalable)
    end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_form.html.slim
= simple_form_for(@room) do |f|
  = f.error_notification

  .form-inputs
    = f.input :room_no
    = f.label :available
    = f.check_box :avalable

  .form-actions
    = f.button :submit

app/views/rooms/edit.html.slim
div.row
	div.col-lg-4
	div.col-lg-4

		h1 Editing room

		== render 'form'

		= link_to 'Show', @room
		'  |
		= link_to 'Back', rooms_path

app/views/rooms/index.html.erb
  <div id="page-wrapper" >
            <div id="page-inner">
                <div class="row">
                    <div class="col-md-12">
                     <h2>All Rooms</h2>   
                        <h5>Welcome , Love to see you back. </h5>
                       
                    </div>
                </div>
                 <!-- /. ROW  -->
                 <hr />
               
            <div class="row">
                <div class="col-md-12">
                    <!-- Advanced Tables -->
                    <div class="panel panel-default">
                        <div class="panel-heading">
                             
                             <%= link_to 'Add New Room' , new_room_path , class: "btn btn-success btn " %> 
                        </div>
                        <div class="panel-body">
                            <div class="table-responsive">
                                <table class=" datatable table table-striped table-bordered table-hover datatable" id="dataTables-example ">
                                    <thead>
                                        <tr>
                                            <th>Room No</th>
                                            <th>Available</th>
                                            <th>Edit</th>
                                            <th>Delete</th>                                
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <%- @rooms.each do |r| %>
                                        <tr>
                                            <td>
                                                <%= r.room_no %>
                                            </td>
                                            <td>
                                                <%- if r.avalable %>
                                                <i class="glyphicon glyphicon-ok"></i>
                                                <% else %>
                                                <i class="glyphicon glyphicon-remove"></i>
                                                <% end %>
                                            </td>
                                            <td><%= link_to 'edit' , edit_room_path(r) , class: "btn btn-info btn-xs" %></td>
                                            <td><%= link_to 'delete' , r , method: :delete , class: "btn btn-danger btn-xs" %></td>
                                        </tr>

                                        
                                        <% end %>
                                    </tbody>
                                </table>
                            </div>
                            
                        </div>
                    </div>
                </div>
            </div>

app/views/rooms/new.html.slim
div.row
	div.col-lg-4
	div.col-lg-4
		div.panel.panel-default.panel-cus
			h1 New Room
			hr
			== render 'form'
			br
			hr
			= link_to 'Back', rooms_path , class: "glyphicon glyphicon-arrow-left btn btn-default"

app/views/rooms/show.html.slim
p#notice = notice

p
  strong Room no:
  = @room.room_no
p
  strong Avalable:
  = @room.avalable

= link_to 'Edit', edit_room_path(@room)
'  |
= link_to 'Back', rooms_path